apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wordpress-mysql
  name: wordpress-mysql
spec:
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: wordpress-mysql
  type: ClusterIP
status:
  loadBalancer: {}