apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
  name: wordpress
spec:
  ports:
  - name: "80"
    nodePort: 31004
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: wordpress
  type: NodePort
status:
  loadBalancer: {}
